FIX #29 visualizar setores
fga-gpp-mds/2018.1-Dulce_API pull request #33
Opened 2018-04-28 00:54 UTC by vitorl-s

Nesse PR foi feito:
#29

2018-04-28 01:31 UTC, gag2502 requested changes
- Pasta src não deveria existir. Não faz sentido
Cada diretório é um serviço. Não há pastas compartilhadas.
- Retirar console.logs()

2018-04-28 01:35 UTC, gabibguedes commented
Gabi, essa pasta src já estava na api, n foi adicionada nessa branch

2018-04-28 02:01 UTC, vitorl-s commented
@gag2502 ja foi retirado tudo!

2018-04-29 00:42 UTC, gag2502 requested changes
Nesse código vocês criaram uma nova base para setores, dessa forma não é possível utilizar o token gerado ao efetuar login e criar o novo setor

2018-04-29 03:01 UTC, gag2502 approved these changes
PR aceito

2018-04-29 03:02 UTC, merged